services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    environment:
      - APP_ENV=dev
      - DB_URL=sqlite:///./data.db
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules           # FIX: preserva le deps nel container
    ports:
      - "3000:3000"
    command: npm run dev